# Site settings
title: John Folkers
# twitter_username: rob_hinds
name: John Folkers

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
#primarylinks:
# - title: Blog
#   url: https://automateddeveloper.blogspot.com/
# - title: GitHub
#   url: https://github.com/robhinds
# - title: StackOverflow
#   url: https://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
# - title: LinkedIn
#   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1
# - title: Food
#   url: https://www.robbishfood.com/

#Any buzzword skills you want to include
skills:
 - AWS
 - Business Intelligence
 - C#
 - Databricks
 - Data Mining
 - Data Modeling
 - Graph Databases/Cypher
 - Jupyter Lab
 - KNIME
 - Machine Learning
 - NiFi
 - Splunk
 - SQL
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Senior Engineer
   start: 2019
   end: Ongoing
   employer: Dimensional Fund Advisors
#   description:
 - title: Lead BI Analyst
   start: 2016
   end: 2019
   employer: Zenimax Media
   description: Zenimax HQ role working with id Software AAA Quake Champions data analysis using a number of machine learning techniques.
 - title: Splunk Architect
   start: 2013
   end: 2016
   employer: Zenimax Online Studios
   description: I worked closely with the game studio in all aspects of the technology including the centralized logging and back-end services.
 - title: Customer Engineer
   start: 2012
   end: 2013
   employer: Infusionsoft
   description: Working on a range of functional and technical roles, primarily working onboarding client data.
 - title: Professional Services
   start: 2011
   end: 2012
   employer: Splunk
   description: Fantastic experience deploying Splunk and educating new customers.

#Education is required
education:
 - level: Certificate
#   date: 
   subject: Data Science for Business
   school: Business Science University
 - level: Associate of Science (A.S.)
#   date: 
   subject: Computer Programming
   school: Columbus State Community College

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
# github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
# stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro:
Currently working as an engineer in technology for research and development topics using a range of cutting edge technology and techniques including C#, Python, Jupyter Lab/R Studio, Machine Learning/AI, Graph Databases. I have previously worked with a range of languages and platforms including Splunk, Databricks, NiFi, AWS, SQL.
I was lead data analyst on the data science team for the AAA game Quake Champions, and prior to that I led the Splunk rollout as the Splunk architect for two AAA rated games Elder Scrolls Online and Fallout 76.
I also co-founded Data Ice Cream LLC (parked).

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo:
   <strong>Graph Databases</strong>: My current role uses Cypher and SQL as primary languages as well as C# and Python in Jupyter Lab and also Machine Learning H2O in R Studio and have been analyzing forensic data in ServiceNow, DependencyTrack and Elastic for the last three years. I am familiar with a range of Graph databases, such as <a target="_blank" href="https://www.graphistry.com/"> Graphistry for exploratory data analysis (EDA)</a> and <a target="_blank" href="https://age.apache.org/">A Graph Extension for PostgreSQL</a>, as well as familar with a range of <a target="_blank" href="https://en.wikipedia.org/wiki/Cypher_(query_language)" >graph database languages</a>.<br/><br/>
   <strong>R Studio</strong>: I am experienced in a variety of Machine Learning frameworks when I went to work on id Software's <a target='_blank' href="https://www.elderscrollsonline.com">AAA game Quake Champions</a> in R Studio and Databricks. I have worked with H2O suite of Machine Learning model tools the most.<br/><br/>
   <strong>Splunk</strong> I have architected Splunk deployments since Splunk 3.x in 2010, and deployed Splunk in production since version 4.x from 2011 and onward. I am the architect who built Splunk for <a target='_blank' href="https://www.elderscrollsonline.com">AAA game Elder Scrolls Online</a> and <a target="_blank" href="https://fallout.bethesda.net/">AAA game Fallout</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have used both AWS and Azure for running production data analysis on the cloud. I have experience with Azure's blobs and also using a range of AWS offerings, including EC2, S3, AWS CLI, AWS Management Console as administrator for production, staging, development.<br/><br/>
   <strong>Web Development</strong>: Mostly this is turning Jupyter notebooks into Dashboards: either through Voila + Graphistry, or it could be with Jupyter Dash. I have taken online courses, and I have also worked with various web technologies. Most recently I have written React applications (primarily using the Create React App framework, and extending them).<br/><br/>
   <strong>Networks and Operating Systems</strong>: I have a good knowledge of networks and operating systems from my previous professional careers having worked with firewalls routers and switches, bluecoats and reverse proxies, Windows, Linux and MacOSX, and have worked in several disaster recovery sites having set up the network operationally.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including FFMPEG with its commandline style of video and audio editing and compression, cutting and swapping out audio codecs, video codecs and reducing the size on disk. I can also do size reduction for PDFs using free open source tools.<br/><br/>
   
